### ISSUE TITLE
Dead slow 

### ISSUE THREAD

**Issue by poorvajappja** [h-mdm/apuppet-android#1]
I used this app but , the screen stream was very slow.

Improve this.

**Comment by poorvajappja** [comment]
I am using android 11 but , audio stream not working.

**Comment by poorvajappja** [comment]
I checked with 3 android devices very slow and its not user friendly. 

This project needs lot of
 improvements.

**Comment by poorvajappja** [comment]
Some time it automatically disconnect

**Comment by poorvajappja** [comment]
Most of the time it comes like this

![20210321_094347](https://user-images.githubusercontent.com/65843311/111893727-a2d41680-8a2a-11eb-8077-22519072cbdd.jpg)

**Comment by h-mdm** [comment]
APuppet doesn't translate any audio stream from the device.

Here are a few hints which may help.

1. Turn on the "Flash while sharing" option in the mobile application settings. A static picture (the most of Android screens are static) is not translated well on some devices.
2. Reduce the bitrate, this may help if your network connection is unstable and/or slow.
3. Make sure your device is connected via WiFi or at least 3G mobile connection. 2G connections are too slow to send a video stream.
4. Consider setting up your own instance of aPuppet server.

**Comment by dfun90** [comment]
@poorvajappja One thing I have noticed in our case is that you can not simultaneously have an active remote support session and a phone call running, it always breaks the remote support session since it seems too much to handle for the phone.
