### ISSUE TITLE
Is there a method to remove existing room to solve room already-exist issue

### ISSUE THREAD

**Issue by FJEagle** [h-mdm/apuppet-android#2]
We are trying to use a assigned fixed session id and password repeatedly for a android client.

At the begining, all worked fine, but the client failed to connect to server after a while due to errorReason(=2).

According to the janus backend log, we guess that the android client failed to destroy the previous room for some reason.

Therefore, we wonder is there a method to remove the already-exsit room explicitly to avoid the error?

Janus related error log:
`
[Thu Jun 24 01:42:20 2021] [8338932222981133] SCTP data received of length 118 on channel with id 0.
[Thu Jun 24 01:42:20 2021] Got a DataChannel message (118 bytes): {"textroom":"create","is_private":false,"permanent":false,"transaction":"816996005481","room":"A0091750","pin":"1234"}
[Thu Jun 24 01:42:20 2021] [ERR] [plugins/janus_textroom.c:janus_textroom_handle_incoming_request:2388] Room A0091750 already exists!
[Thu Jun 24 01:42:20 2021] [8338932222981133] SCTP data to send (label=JanusDataChannel, 126 bytes) coming from a plugin.
[Thu Jun 24 01:42:20 2021] [8338932222981133]   -- Using open channel 1
[Thu Jun 24 01:42:20 2021] [8338932222981133] Message sent on channel 1`

**Comment by h-mdm** [comment]
Here is the removal method: JanusTextRoomPlugin.destroyViaHttp(). After you're getting the error message, you need to send a destroy message with the corresponding room ID in the same session, and retry creating a room after the destroy is successful.
